version: '2'
services:
  node1:
    environment:
      - NAME=1
      - HOST=0.0.0.0
    image: rlkamradt/naivecoin
    ports:
    - "3001:3001"
    volumes:
    - ./:/naivecoin
    networks:
     - network
  node2:
    environment:
      - HOST=0.0.0.0
      - NAME=2
      - PEERS=http://node1:3001
    image: rlkamradt/naivecoin
    ports:
    - "3002:3001"
    volumes:
    - ./:/naivecoin
    networks:
     - network
  node3:
    environment:
      - HOST=0.0.0.0
      - NAME=3
      - PEERS=http://node2:3001
    image: rlkamradt/naivecoin
    ports:
    - "3003:3001"
    volumes:
    - ./:/naivecoin
    networks:
     - network
networks:
  network:
